### ISSUE TITLE
Essay Tickets Don't Close

### ISSUE THREAD

**Issue by freidsnarecool** [School-Simplified/Timmy-SchoolSimplified#103]
### Discord Username

Discord Username:  additionalsink#8104  ID: 342319615382257664

### Summary

essay tickets won't close. the transcript gets saved, but the tickets don't close and delete when we press "close and delete"

### Feature Type

Interactions (Buttons, Slash Commands, Dropdown)

### Reproduction Steps

um i pressed the button "close and delete" when staff commands show up, but the ticket consistently don't close (they get saved, but don't close) 

### Reproducible Command

![image](https://user-images.githubusercontent.com/95946631/145657519-6028ab8e-2cec-4cef-8fed-3ca65d689f2b.png)

### Expected Results

the ticket should have closed the deleted 

### Actual Results

nothing happens :sob

### Location

many of the essay tickets in the School Simplified Server (example, #essay-reviser-932)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I know that I am authorized to perform that command and looked at the documentation to make sure I have done the command correctly.
- [X] I have tried the same command/interaction AGAIN after waiting a bit.

**Comment by Space-Turtle0** [comment]
Traceback Confirmed: 

```py
Traceback (most recent call last):
  File "/Users/space/Documents/GitHub/Timmy-SchoolSimplified/TimmyVenv/lib/python3.8/site-packages/discord/client.py", line 357, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "/Users/space/Documents/GitHub/Timmy-SchoolSimplified/TimmyVenv/lib/python3.8/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/Users/space/Documents/GitHub/Timmy-SchoolSimplified/utils/events/TicketDropdown.py", line 928, in TicketDropdown
    opened_at = datetime.strftime(opened_at_raw, "%Y-%m-%d\n%I.%M %p")
TypeError: descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'NoneType' object
```

**Comment by Space-Turtle0** [comment]
Migration script ran, looks like it worked!
@freidsnarecool #essay-revisor-932 got deleted, if the issue persists with other channels could you try clicking the close button again?
