### ISSUE TITLE
Port over to slash commands

### ISSUE THREAD

**Issue by Space-Turtle0** [School-Simplified/Timmy-SchoolSimplified#107]
Eventually, we want to deploy slash commands alongside text commands, but in the end migrate everything **just** to slash commands!

- [x] Slash Commands Migration
    - [x] Migrate from `ctx` to `interaction`
    - [x] Migrate checks.
    - [x] Add command groups and descriptions for each command.
    - [x] Add normal command handler to redirect users to slash commands.
- [x] Rollout Slash Commands to **public**.
- [x] Archive original text commands.

**Comment by pandabear189** [comment]
slash cmd porting - assigned to me

**Comment by Space-Turtle0** [comment]
#107 shouldn't be prioritized at the moment, PyCord has a bunch of internal errors with slash command management. Until those issues are fixed, let's avoid slash command integrations.

**Comment by pandabear189** [comment]
removed from milestone due to slash cmd internal errors

**Comment by pandabear189** [comment]
restarting,

**Comment by Puncher1** [comment]
Split it in to section. Slash commands and regular commands. Regular commands will send a message that it's deprecated
