### ISSUE TITLE
Code Guidelines Documentation

### ISSUE THREAD

**Issue by pandabear189** [School-Simplified/Timmy-SchoolSimplified#142]
\+ split up `common.py` to multiple files

**Comment by Space-Turtle0** [comment]
I intend to auto PEP 8 everything via #135 eventually. 

Although in the meanwhile, members should be using something PEP 8 compliant when linting. 
EX: https://black.readthedocs.io/en/stable/getting_started.html

**Comment by Puncher1** [comment]
I'm currently creating Code Guidelines which are based on PEP8. After that I/we will rewrite the code (I'll make another issue for that)
