### ISSUE TITLE
Add Music Bot via Discord VC Games

### ISSUE THREAD

**Issue by Space-Turtle0** [School-Simplified/Timmy-SchoolSimplified#148]

**Comment by pandabear189** [comment]
what do u mean by this? like create a discord game?

**Comment by Space-Turtle0** [comment]
Yeah, instead of making an actual music bot. We can just use this and let discord handle making playlists and playing songs.
> https://docs.pycord.dev/en/master/api.html?highlight=youtube%20together#discord.EmbeddedActivity.watch_together

**Comment by pandabear189** [comment]
ok 👍

**Comment by Space-Turtle0** [comment]
Fixed in 91e1fa6.
