### ISSUE TITLE
Auto unarchive threads

### ISSUE THREAD

**Issue by Puncher1** [School-Simplified/Timmy-SchoolSimplified#152]
### Discord Username

Discord Username:  Puncher#1111  ID: 305354423801217025

### Summary

Auto unarchive threads

### Feature Type

Other (Database, Voice Channels, Data Parsing)

### Current Solution

@Space-Turtle0 is sending every day "unarchive" in the archived threads. 

### Current Issue

You have to write every day a message to unarchive.

### Suggested Solution

Auto archive with the bot. 

The bot is in a loop, he checks every minute if the the threads are archived or not. (I first though't 1h is enough, but if the bot gets restarted, the loop gets restarted too). There's an attribute called `archived` which returns a `bool`, so basically you check every minute every thread if it's archived with `Thread.archived` and if it returns `True`, the bot sends a message into that thread and deletes it instantly again.

### Checklist

- [X] I have searched the open issues for duplicates.

### Additional Context

-

**Comment by Space-Turtle0** [comment]
Fixed in 87b9ba1
