### ISSUE TITLE
Fix gitpull cmd

### ISSUE THREAD

**Issue by pandabear189** [School-Simplified/Timmy-SchoolSimplified#156]
### Discord Username

Discord Username:   - ID: -

### Summary

-

### Feature Type

Commands

### Reproduction Steps

-

### Reproducible Command

-

### Expected Results

-

### Actual Results

-

### Location

-

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I know that I am authorized to perform that command and looked at the documentation to make sure I have done the command correctly.
- [X] I have tried the same command/interaction AGAIN after waiting a bit.

**Comment by Puncher1** [comment]
Fixed it
