### ISSUE TITLE
[TUTOR VC BUG]

### ISSUE THREAD

**Issue by Yelloo5191** [School-Simplified/Timmy-SchoolSimplified#17]
**FILL OUT THE FIELDS BELOW!**

**Discord Username and Tag**
Yelloooooooo#3477

**Describe the bug**
When scheduling a session, if the scheduler were to choose a date that has already passed, the command goes through and they get spammed with dms that warn of the "upcoming" session.

**To Reproduce**
run command:
`+schedule 08/24 1:00 AM <@304024578009595907> science False`

**Expected behavior**
Prevent the user from scheduling a date that has already passed

**Screenshots**
![image](https://user-images.githubusercontent.com/76452706/129499551-88f86651-e132-47fd-87c8-e86739869ad4.png)
![image](https://user-images.githubusercontent.com/76452706/129499557-5ba85ab6-900b-438f-82f7-5c7679fb5f59.png)

**Additional context**
n/a

**Comment by Space-Turtle0** [comment]
The bug has been fixed, the commit is attached above.
