### ISSUE TITLE
Add Descriptions to Commands

### ISSUE THREAD

**Issue by TimmyOS** [School-Simplified/Timmy-SchoolSimplified#263]
**Issue Feature**
Other

**Issue Title**
Add Descriptions to Commands

**Issue Summary**
Adding command descriptions so they show up on help command. This can be done with descriptions kwarg or docstring under command function

**Additional Context**
None

https://cdn.discordapp.com/ephemeral-attachments/963610652268707921/964557616988713020/Screenshot_2022-04-15_110731.jpg

**Comment by Space-Turtle0** [comment]
Merge with issue #107 
Slash commands will require a description anyway.
