### ISSUE TITLE
cameron.. | 567057930537402378 Issue/Feedback

### ISSUE THREAD

**Issue by TimmyOS** [School-Simplified/Timmy-SchoolSimplified#269]
**Feedback:**

- User Action: Make staff emails.

- Steps to reproduce the issue: Utilize /g-suitecreate and follow the steps to make an account.

- What happened: Given an error message.

- Expected Result: G-Suite account was supposed to be created.

- Anything else: 

- Gist: https://gist.github.com/3dbc29383fc29849603806cbf36f7692

**Comment by Space-Turtle0** [comment]
Semi-valid error. 

The user already exists, so we're getting back a 409, but it also represents the issue with a lack of error handling. 
Nonetheless, taken care of.
